name: Complex Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'Alan Amirtharaj'
      environment:
        description: 'Choose the environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
          - testing
          - QA
          -UAT

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Enhanced PowerShell Script
        run: |
          pwsh -File ./enhanced_script.ps1 -Name '${{ github.event.inputs.name }}' -Environment '${{ github.event.inputs.environment }}'
